/* Service worker for the gpui-starter wasm harness (classic script, no deps).
 *
 * VERSION SCHEME: serve_http.py injects the real build hash into
 * `BUILD_VERSION` below (from wasm/pkg/version.json, generated by
 * wasm/precompress.mjs) every time /sw.js is served, and /sw.js is always
 * sent with `Cache-Control: no-store` — so after a deploy the browser's
 * routine SW update check sees different bytes, runs the install/activate
 * cycle, and the new SW postMessages the page, which shows the
 * "New version available — Reload" toast (see index.html).
 *
 * DEV MODE: without version.json (plain `wasm/build.sh` debug builds) the
 * served script keeps BUILD_VERSION = null and the SW is a no-op — caching a
 * ~95 MB debug wasm on every iteration would be pointless. Registration
 * still succeeds, so installability (manifest + SW) holds in dev too.
 */
"use strict";

// Injected by serve_http.py from wasm/pkg/version.json (null in dev mode).
var BUILD_VERSION = null;

// Absolute pathnames (the SW scope is the harness root): used both for
// install-time precache URLs and for the fetch-handler shell match below —
// request URLs arrive as absolute pathnames, so "./"-style relatives would
// never compare equal. /pkg/* is matched by prefix separately.
var SHELL_PATHS = [
  "/",
  "/index.html",
  "/manifest.webmanifest",
  "/pkg/version.json",
  "/icons/icon.svg",
  "/icons/icon-192.png",
  "/icons/icon-512.png",
  "/icons/icon-512-maskable.png",
];

var DEV = !BUILD_VERSION;
var SHELL_CACHE = DEV ? null : "gpui-starter-shell-" + BUILD_VERSION;
var RUNTIME_CACHE = "gpui-starter-runtime";

self.addEventListener("install", function (event) {
  if (DEV) {
    self.skipWaiting();
    return;
  }
  event.waitUntil(
    (async function () {
      var cache = await caches.open(SHELL_CACHE);
      // 'reload' bypasses any intermediate HTTP cache; the harness server
      // sends no-store anyway, but be explicit for other hosts.
      await cache.addAll(
        SHELL_PATHS.map(function (p) {
          return new Request(p, { cache: "reload" });
        })
      );
      await self.skipWaiting();
    })()
  );
});

self.addEventListener("activate", function (event) {
  event.waitUntil(
    (async function () {
      var keep = DEV ? [] : [SHELL_CACHE, RUNTIME_CACHE];
      var names = await caches.keys();
      await Promise.all(
        names.map(function (n) {
          if (keep.indexOf(n) === -1) return caches.delete(n);
        })
      );
      await self.clients.claim();
      if (DEV) return;
      // Tell open pages a new build took control -> toast + reload offer.
      // (index.html compares this against the version the page booted with,
      // so a first-ever install never nags.)
      var clients = await self.clients.matchAll({ includeUncontrolled: true });
      clients.forEach(function (c) {
        c.postMessage({ type: "update-available", version: BUILD_VERSION });
      });
    })()
  );
});

self.addEventListener("fetch", function (event) {
  if (DEV) return; // pass straight through to the network
  var req = event.request;
  if (req.method !== "GET") return;
  var url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  var isShell =
    SHELL_PATHS.indexOf(url.pathname) !== -1 ||
    url.pathname.indexOf("/pkg/") === 0;
  if (isShell) {
    // Cache-first: caches are keyed by build hash, so a fresh build means a
    // fresh SW (see header comment) — stale entries never outlive a deploy.
    event.respondWith(
      caches.open(SHELL_CACHE).then(function (cache) {
        return cache.match(req, { ignoreSearch: true }).then(function (hit) {
          return (
            hit ||
            fetch(req).then(function (res) {
              if (res && res.ok) cache.put(req, res.clone());
              return res;
            })
          );
        });
      })
    );
    return;
  }
  // Other same-origin GETs (runtime assets): network-first, offline fallback.
  event.respondWith(
    fetch(req)
      .then(function (res) {
        if (res && res.ok && res.type === "basic") {
          caches.open(RUNTIME_CACHE).then(function (cache) {
            cache.put(req, res.clone());
          });
        }
        return res;
      })
      .catch(function () {
        return caches.match(req, { ignoreSearch: true }).then(function (hit) {
          return hit || Response.error();
        });
      })
  );
});

// Page-driven messages: 'get-version' (which build is serving this page)
// and 'check-update' (compare the networked version.json against the build
// this SW was installed for).
self.addEventListener("message", function (event) {
  var data = event.data;
  if (!data || typeof data.type !== "string") return;
  if (data.type === "get-version") {
    event.source &&
      event.source.postMessage({ type: "sw-version", version: BUILD_VERSION });
    return;
  }
  if (data.type !== "check-update" || DEV) return;
  event.waitUntil(
    (async function () {
      try {
        var res = await fetch("./pkg/version.json", { cache: "no-store" });
        if (!res.ok) return;
        var info = await res.json();
        if (info && info.version && info.version !== BUILD_VERSION) {
          event.source &&
            event.source.postMessage({
              type: "update-available",
              version: info.version,
            });
        }
      } catch (e) {
        /* offline / server gone — nothing to report */
      }
    })()
  );
});
